model_name: "llava-hf/llava-1.5-7b-hf"
device: "cuda"

# optional arguments passed to `from_pretrained`
model_kwargs: {}

extraction_layer: "model.layers.30"
data_sources:
  toxic_neutral_pairs: "data/toxic_neutral_pairs.jsonl"  # or "user/dataset:split"
  multimodal_test_cases: "data/multimodal_test_cases.jsonl"  # or "user/dataset:split"

intervention_layer: "model.layers.30"
intervention_multiplier: 1.2

output_dir: "results/"
